INSERT INTO banks(
    swift_code, address, bank_name, countryiso2, country_name, is_headquarter
) VALUES
      ('AAISALTRXXX', 'HYRJA 3 RR. DRITAN HOXHA ND. 11 TIRANA, TIRANA, 1023','UNITED BANK OF ALBANIA SH.A', 'AL', 'ALBANIA', true),
      ('ABIEBGS1XXX', 'TSAR ASEN 20  VARNA, VARNA, 9002','ABV INVESTMENTS LTD', 'AL', 'BULGARIA', true),
      ('BBVAUYMMXXX','25 DE MAYO, ESQUINA ZAQBALA 401  MONTEVIDEO, MONTEVIDEO, 11000','BANCO BILBAO VIZCAYA ARGENTARIA URUGUAY S.A.','UY','URUGUAY',true),
      ('BCHICLR10R2','','BANCO DE CHILE','CL','CHILE',false ),
      ('BNPAPLPXXXX','UL. WRONIA 31  WARSZAWA, MAZOWIECKIE, 00-846','BNP PARIBAS S.A. BRANCH IN POLAND','PL','POLAND', true ),
      ('BREXPLPWMBK','SKRYTKA POCZTOWA 2108  LODZ, LODZKIE, 90-959','MBANK S.A. (FORMERLY BRE BANK S.A.)','PL','POLAND',false ),
      ('BREXPLPWWAL','SIENKIEWICZA 2  WALBRZYCH, DOLNOSLASKIE, 58-300','MBANK S.A. (FORMERLY BRE BANK S.A.)','PL','POLAND',false ),
      ('BREXPLPWXXX','UL. PROSTA 18  WARSZAWA, MAZOWIECKIE, 00-850','MBANK S.A. (FORMERLY BRE BANK S.A.)','PL','POLAND',true ),
      ('BSCHCLR10R7','','BANCO SANTANDER CHILE','CL','CHILE', false),
      ('CBARAWAWXXX','J.E. IRAUSQUIN 8  - ORANJESTAD ORANJESTAD-WEST AND ORANJESTAD-EAST ','CENTRALE BANK VAN ARUBA','AW','ARUBA',true ),
      ('CITIPLPXXXX','SENATORSKA 16  WARSZAWA, MAZOWIECKIE, 00-923','BANK HANDLOWY W WARSZAWIE SA','PL','POLAND',true ),
      ('COMEUYMMALL','  MONTEVIDEO, MONTEVIDEO','SCOTIABANK URUGUAY S.A.','UY','URUGUAY',false ),
      ('COMEUYMMXXX','MISIONES 1399  MONTEVIDEO, MONTEVIDEO, 11000','SCOTIABANK URUGUAY S.A.','UY','URUGUAY',true);
